package templates

var WireSetGenTemplate = `
// Code generated by go-wireset-gen. DO NOT EDIT.

package {{.PackageName}}

import (
    {{ range .Imports }}
    {{- .Alias }} "{{- .Path }}"
    {{ end }}
    "{{- "github.com/google/wire" }}"
)

{{ range .WireSets }}
var {{.SetName}}Set = wire.NewSet(
    {{ range .FuncPath }}
    {{- .}},
    {{ end }}
)
{{ end }}
`