// Code generated by mockery. DO NOT EDIT.

package mock_generator

import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// GenerateWireSet provides a mock function with given fields: verbose
func (_m *Service) GenerateWireSet(verbose bool) error {
	ret := _m.Called(verbose)

	if len(ret) == 0 {
		panic("no return value specified for GenerateWireSet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(bool) error); ok {
		r0 = rf(verbose)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Service_GenerateWireSet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateWireSet'
type Service_GenerateWireSet_Call struct {
	*mock.Call
}

// GenerateWireSet is a helper method to define mock.On call
//   - verbose bool
func (_e *Service_Expecter) GenerateWireSet(verbose interface{}) *Service_GenerateWireSet_Call {
	return &Service_GenerateWireSet_Call{Call: _e.mock.On("GenerateWireSet", verbose)}
}

func (_c *Service_GenerateWireSet_Call) Run(run func(verbose bool)) *Service_GenerateWireSet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(bool))
	})
	return _c
}

func (_c *Service_GenerateWireSet_Call) Return(_a0 error) *Service_GenerateWireSet_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Service_GenerateWireSet_Call) RunAndReturn(run func(bool) error) *Service_GenerateWireSet_Call {
	_c.Call.Return(run)
	return _c
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
